### ISSUE TITLE
client crashes my process on internal assertions

### ISSUE THREAD

**Issue by mcavage** [alexguan/node-zookeeper-client#23]
Hello,

I maintain [zkplus](https://github.com/mcavage/node-zkplus), which several large(ish) consumers of Zookeeper use in node to interact with the ZK API.  I recently made a side project to port to this library as opposed to the native one, since the native one is riddled with bugs, and exacerbated by poor interactions with libuv.  However, upon testing with lots of states where Zookeeper is offline, I am able to reproduce crashes that resemble this (note that the specific error code is non-deterministic, leading me to believe you are either incorrectly parsing Jute or have parsing logic where your offset gets mangled):

```
/Users/mcavage/work/registrar/node_modules/zkplus/node_modules/node-zookeeper-client/lib/Exception.js:51
        throw new Error('Unknown code: ' + code);
              ^
Error: Unknown code: 935133184
    at validateCode (/Users/mcavage/work/registrar/node_modules/zkplus/node_modules/node-zookeeper-client/lib/Exception.js:51:15)
    at Function.create (/Users/mcavage/work/registrar/node_modules/zkplus/node_modules/node-zookeeper-client/lib/Exception.js:140:5)
    at ConnectionManager.onSocketData (/Users/mcavage/work/registrar/node_modules/zkplus/node_modules/node-zookeeper-client/lib/ConnectionManager.js:571:35)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
```

The stack trace is pretty much a simple application I was using to drive testing of ephemeral nodes.  Note that this is not at all anything my process/application can act on, as your library is throwing an assertion on itself: https://github.com/alexguan/node-zookeeper-client/blob/master/lib/Exception.js#L51

I don't have a very good way of reproducing this behavior, other than to note that it only happens when I create a client and connect it with a down zookeeper, wait some number of seconds-minutes and start the Zookeeper.

In the absence of figuring out repro and/or root cause (which I will open as a separate issue), can you please change the various uses of `throw` in the library to `emit('error')` from the client?  This would at least enable me to detect your client is in a bad state and move forward, short of relying on a process restart.

**Comment by jimbobhickville** [comment]
I agree.  This behavior is causing us a lot of problems as well.  It seems to hit a lot of unknown codes and there's no way to trap the exceptions because they're thrown from async code.

**Comment by progman32** [comment]
We're in a similar boat as mcavage: trying to replace the problematic native zookeeper library with this pure-js one. We'll experiment with changing `throw` to `emit('error')` for now.

**Comment by enicholson** [comment]
I've recently seen this from kafka-node during a rolling zookeeper upgrade.  Has there been any progress?

**Comment by gilpeleg** [comment]
Hey,
I encounter this problem as well, will this be fixed in an official release?

Thanks!
