### ISSUE TITLE
NO_NODE error on kafka consumer init.

### ISSUE THREAD

**Issue by madhavan020985** [alexguan/node-zookeeper-client#34]
````javascript
var kafka = require('kafka-node'),
Consumer = kafka.Consumer,
client = new kafka.Client(),
consumer = new Consumer(
  client,
  [
    { topic: '1234', partition: 0 }
  ]
);
consumer.on('message', function (message) {
  console.log(message);
});
````
Kafka consumer created using the above code crashes with NO_NODE[-101] error. 
````javascript
Exception: NO_NODE[-101]
    at ConnectionManager.onSocketData (/home/sk/ws/kafka/node_modules/kafka-node/node_modules/node-zookeeper-client/lib/ConnectionManager.js:570:23)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)
````
More  information on the node path that is not found will help a lot....

**Comment by alexguan** [comment]
Seems like a `karfa-node` issue, have you checked with that module's author?

**Comment by madhavan020985** [comment]
Raised issue#148 @https://github.com/SOHU-Co/kafka-node/
