### ISSUE TITLE
node crashes when zookeeper sends an empty message

### ISSUE THREAD

**Issue by david-knipe-hp** [alexguan/node-zookeeper-client#39]
I'm using node-zookeeper-client version 0.2.1. I've got the following stacktrace:

Error: offset: 4 is out of buffer range.
	at Record.deserialize (/opt/Autonomy/shared/zookeeper-ext/node_modules/node-zookeeper-client/lib/jute/index.js:465:15)
	at ConnectionManager.onSocketData (/opt/Autonomy/shared/zookeeper-ext/node_modules/node-zookeeper-client/lib/ConnectionManager.js:456:34)
	at ConnectionManager.onSocketData (/opt/Autonomy/shared/zookeeper-ext/node_modules/node-zookeeper-client/lib/ConnectionManager.js:580:14)
	at Socket.EventEmitter.emit (events.js:95:17)
	at Socket.<anonymous> (_stream_readable.js:745:14)
	at Socket.EventEmitter.emit (events.js:92:17)
	at emitReadable_ (_stream_readable.js:407:10)
	at emitReadable (_stream_readable.js:403:5)
	at readableAddChunk (_stream_readable.js:165:9)
	at Socket.Readable.push (_stream_readable.js:127:10)
	at TCP.onread (net.js:528:21)

It seems zookeeper is sending an empty message which causes the client to throw. I don't think throwing an exception is the right thing to do just because a separate process gave you some data you didn't like. Especially since the exception is thrown from a handler and therefore can't be caught by the code that's calling node-zookeeper-client. And especially since (AFAICT) the interface with the server isn't documented.

This happened just after we briefly lost contact with the zookeeper server. I believe that https://issues.apache.org/jira/browse/ZOOKEEPER-1437 addresses the same server-side bug (but in a completely different client).

**Comment by alexguan** [comment]
Could you tell me a little bit more of how to reproduce it? Which version of zookeeper are you using? What's the size of your zookeeper quorum?

**Comment by david-knipe-hp** [comment]
Zookeeper is version 3.4.5. Quorum is 2. To be honest I haven't managed to reproduce it, and I'm told it has possibly only happened once. The link I posted may have a way to reproduce it buried in there somewhere, but I'm having trouble following their thread because I don't know anything about the java client. But even if it can't be reproduced, I still don't think you should have blocks that say "if the input was wrong, crash the process".
