### ISSUE TITLE
Unknown code: -1237188481

### ISSUE THREAD

**Issue by amitmtrn** [alexguan/node-zookeeper-client#70]
I've got this weird exception:

```
2017-12-24T14:15:37.021Z - error: uncaughtException Error: Unknown code: -1237188481
    at validateCode (project-folder/node_modules/node-zookeeper-client/lib/Exception.js:51:15)
    at Function.create (project-folder/node_modules/node-zookeeper-client/lib/Exception.js:140:5)
    at ConnectionManager.Object.<anonymous>.ConnectionManager.onSocketData (project-folder/node_modules/node-zookeeper-client/lib/ConnectionManager.js:570:35)
```

Not sure if it's related to this package since I'm using (https://www.npmjs.com/package/kafka-node)[kafka-node].
I'm also not sure what causes it; I'm just sending a message and listen to the message (straightforward use case).

**Comment by GrayGuo** [comment]
I'm seeing similar exception as well, with different code `-321257332`, running Node.js v6.11.5 on Linux

```
/app/node_modules/node-zookeeper-client/lib/Exception.js:51
        throw new Error('Unknown code: ' + code);
        ^
 Error: Unknown code: -321257332
    at validateCode (/app/node_modules/node-zookeeper-client/lib/Exception.js:51:15)
    at Function.create (/app/node_modules/node-zookeeper-client/lib/Exception.js:140:5)
    at ConnectionManager.onSocketData (/app/node_modules/node-zookeeper-client/lib/ConnectionManager.js:570:35)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

**Comment by Catlite91** [comment]
+1

**Comment by fbo3264** [comment]
+1

**Comment by alexguan** [comment]
What version of the zookeeper are you using? What operations were you doing when the exception happened?

**Comment by fbo3264** [comment]
@alexguan I was able to solve the issue. Unintentionally I was opening several zookeeper-connections almost at the same time, i.e. while the connect()-call was still in progress. It works fine now :)

**Comment by GrayGuo** [comment]
@alexguan I'm using `node-zookeeper-client@0.2.2` and the code simply does `connect()` to the Zookeeper server.

**Comment by Catlite91** [comment]
Some useful infomation:
step1. Create ZkClient and connect as normal
step2. Disable your network and wait for about 1 min(due to zk heap)
step3. Enable the network will throw this Error

![image](https://user-images.githubusercontent.com/9129944/48596858-c340c180-e995-11e8-8319-4284c2499b35.png)

**Comment by alexguan** [comment]
@Catlite91 which version of zookeeper are you using?

**Comment by Catlite91** [comment]
@alexguan 3.4.8
