### ISSUE TITLE
exception " Index out of range"

### ISSUE THREAD

**Issue by lonelywolf4git** [alexguan/node-zookeeper-client#89]
I use node-zookeeper-client to connect zookeeper which version is 3.4.1(docker), it sometimes throw the following exception "app.js:10
    at checkOffset (buffer.js:972:11)
    at Uint8Array.Buffer.readInt32BE (buffer.js:1137:5)
.....
 at Array.forEach (<anonymous>)
    at constructor.Record.deserialize 
    at ConnectionManager.onSocketData 
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)

I add the console log here 👍 
   case 'buffer':
            try {
                length = buffer.readInt32BE(offset);
            } catch (err) {
                console.log("buffer's length is: " + buffer.length + " offset is " + offset)
                throw err

            }
When throw it , I check the buffer length is 20, and offset is 20 too. 
Can you help to check this ,thanks!

**Comment by rambo-panda** [comment]
+1

**Comment by rambo-panda** [comment]
It should have received abnormal data, right? In this case, it's best to close the socket and reconnect it?
