### ISSUE TITLE
`setMaxListeners` warning

### ISSUE THREAD

**Issue by rambo-panda** [alexguan/node-zookeeper-client#95]
```
((node:78246) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 notification listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:247:17)
    at EventEmitter.addListener (events.js:263:10)
    at EventEmitter.once (events.js:292:8)
    at registerWatcher (/private/tmp/test/node_modules/node-zookeeper-client/lib/WatcherManager.js:37:24)
    at WatcherManager.registerChildWatcher (/private/tmp/test/node_modules/node-zookeeper-client/lib/WatcherManager.js:63:5)
    at ConnectionManager.registerChildWatcher (/private/tmp/test/node_modules/node-zookeeper-client/lib/ConnectionManager.js:177:25)
    at Object.callback (/private/tmp/test/node_modules/node-zookeeper-client/index.js:807:44)
    at ConnectionManager.onSocketData (/private/tmp/test/node_modules/node-zookeeper-client/lib/ConnectionManager.js:563:35)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)

```

**Comment by alexguan** [comment]
Please provide a code example that could reproduce the message, without that it's hard to look into it.
