### ISSUE TITLE
CreateMode not defined

### ISSUE THREAD

**Issue by feitnomore** [alexguan/node-zookeeper-client#99]
When running the example, I'm getting:
```
ReferenceError: CreateMode is not defined
    at Client.<anonymous> (/home/kafka/teste-node/blah.js:12:5)
    at Object.onceWrapper (events.js:299:28)
    at Client.emit (events.js:210:5)
    at Client.defaultStateListener (/home/kafka/teste-node/node_modules/node-zookeeper-client/index.js:55:14)
    at Client.emit (events.js:210:5)
    at Client.onConnectionManagerState (/home/kafka/teste-node/node_modules/node-zookeeper-client/index.js:263:14)
    at ConnectionManager.emit (events.js:210:5)
    at ConnectionManager.setState (/home/kafka/teste-node/node_modules/node-zookeeper-client/lib/ConnectionManager.js:168:14)
    at ConnectionManager.onSocketData (/home/kafka/teste-node/node_modules/node-zookeeper-client/lib/ConnectionManager.js:443:18)
    at Socket.emit (events.js:210:5)
```
Source code:
```
var zookeeper = require('node-zookeeper-client');

var client = zookeeper.createClient('localhost:2181');
var path = process.argv[2];

client.once('connected', function () {
    console.log('Connected to the server.');

zookeeper.create(
    '/test/demo',
    Buffer.from('data'),
    CreateMode.EPHEMERAL,
    function (error, path) {
        if (error) {
            console.log(error.stack);
            return;
        }

        console.log('Node: %s is created.', path);
    }
);
    client.create(path, function (error) {
        if (error) {
            console.log('Failed to create node: %s due to: %s.', path, error);
        } else {
            console.log('Node: %s is successfully created.', path);
        }

        client.close();
    });
});

client.connect();
```

**Comment by feitnomore** [comment]
need to use: zookeeper.CreateMode.XXXXX....
